"""Initial commit

Revision ID: df2a1549d2f9
Revises:
Create Date: 2025-02-18 05:32:06.514613

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from core.database.models.order import OrderTypes

# revision identifiers, used by Alembic.
revision: str = "df2a1549d2f9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def fill_order_types():
    types = ",".join(map(lambda x: f"('{x}')", OrderTypes))
    op.execute(sa.text(f"INSERT INTO order_types (name) VALUES {types}"))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_types",
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_types")),
        sa.UniqueConstraint("name", name=op.f("uq_order_types_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "orders",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("deliver_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["order_types.id"], name=op.f("fk_orders_type_id_order_types")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    fill_order_types()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("users")
    op.drop_table("order_types")
    # ### end Alembic commands ###
