"""Alter order, enchance delivery_price column

Revision ID: ddff1b05016e
Revises: df2a1549d2f9
Create Date: 2025-02-18 19:48:31.955372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ddff1b05016e"
down_revision: Union[str, None] = "df2a1549d2f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("delivery_price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "delivery_price")
    # ### end Alembic commands ###
