"""delivery_id fix

Revision ID: ddb472ee3bcf
Revises: 17d6812f7b62
Create Date: 2025-02-21 03:46:21.423675

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ddb472ee3bcf"
down_revision: Union[str, None] = "17d6812f7b62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "deliver_id", existing_type=mysql.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "deliver_id", existing_type=mysql.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
