"""Fix delivery price from float rubles to integer kopeikas

Revision ID: b8d9d506e565
Revises: ddff1b05016e
Create Date: 2025-02-19 13:56:32.376106

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b8d9d506e565"
down_revision: Union[str, None] = "ddff1b05016e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "delivery_price",
        existing_type=mysql.FLOAT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "delivery_price",
        existing_type=sa.Integer(),
        type_=mysql.FLOAT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
